#!/bin/bash

MONITOR_DEVICE=wlan0
OUTPUT_DEVICE=eth0

# Catch ctrl c so we can exit cleanly
trap ctrl_c INT
function ctrl_c(){
    echo Killing processes..
    pkill dnsmasq
    pkill hostapd
}

ifconfig $MONITOR_DEVICE 10.0.0.1/24 up
dnsmasq -C /etc/dnsmasq.conf -H dns_entries
sysctl -w net.ipv4.ip_forward=1
iptables -P FORWARD ACCEPT
iptables --table nat -A POSTROUTING -o $OUTPUT_DEVICE -j MASQUERADE
hostapd /etc/hostapd/hostapd.conf -B
#tshark -i $MONITOR_DEVICE  -w output.pcap -P
